variables:
  CONTAINER_PROJECT_PATH: /uc1-recruit/list

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

unit:
  stage: test
  image: docker:stable
  extends:
    - .job_defaults
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
  script:
    - docker build --target=test .
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

e2e:
  stage: test
  image:
    name: docker/compose:1.28.0
    entrypoint: [""]
  extends: .job_defaults
  before_script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    # removing babel.config.js prevents the error
    # 'Error: Cannot find module '@vue/cli-plugin-babel/preset' from '/e2e' while rsing file: /e2e/tests/e2e/support/index.js'
    # in cypress
    - rm babel.config.js
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run loader
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run e2e
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml down -v --remove-orphans
