image: docker:stable

variables:
  DOCKER_REGISTRY: docker.miracum.org
  PROJECT_PATH: /uc1-recruit/list
  IMAGE_PATH: $DOCKER_REGISTRY$PROJECT_PATH

.docker_registry:
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME $DOCKER_REGISTRY --password-stdin
  after_script:
    - docker logout $DOCKER_REGISTRY

.job_defaults:
  only:
    - merge_requests
    - master

include:
  - project: "devops/ci-templates"
    file: "/preflight/.tidy-files.yml"
  - project: "devops/ci-templates"
    file: "/linting/.yamllint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.hadolint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.markdownlint.yml"
  - project: "devops/ci-templates"
    file: "/versioning/.semantic-release-get-version.yml"
  - project: "devops/ci-templates"
    file: "/image-scanning/.trivy-scan.yml"

stages:
  - preflight
  - lint
  - version
  - build
  - test
  - release

check file tidiness:
  extends: .job_defaults

hadolint:
  extends: .job_defaults

yamllint:
  extends: .job_defaults

markdownlint:
  extends: .job_defaults

get next version:
  extends: .job_defaults

build:
  stage: build
  extends:
    - .job_defaults
    - .docker_registry
  script:
    - export VERSION=$(cat .VERSION)
    - docker build -t $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
      --build-arg VERSION=$VERSION
      --build-arg GIT_REF=$CI_COMMIT_SHA
      --build-arg BUILD_TIME="$(date -Is)" .
    - docker push $IMAGE_PATH:$CI_COMMIT_SHORT_SHA

trivy:
  extends: .job_defaults
  allow_failure: true
  variables:
    IMAGE_FQN: $DOCKER_REGISTRY$PROJECT_PATH:$CI_COMMIT_SHORT_SHA

unit:
  stage: test
  extends: .job_defaults
  script:
    - export VERSION=$(cat .VERSION)
    - export DOCKER_BUILDKIT=1
    - docker build --build-arg VERSION=$VERSION -f tests/unit/Dockerfile .
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

e2e:
  image:
    name: docker/compose:1.25.5
    entrypoint: [""]
  stage: test
  extends: .job_defaults
  before_script:
    # ideally, we should instead allow for mounting the build directory directly.
    - export E2E_PATH=/cache/uc1/recruit/$CI_PROJECT_NAME/$CI_JOB_ID
    - mkdir -p $E2E_PATH
    - cp -r tests/ $E2E_PATH
    - cp cypress.json $E2E_PATH
    - cp -r deploy/ $E2E_PATH
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run loader
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run e2e
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml down --remove-orphans
    - rm -rf /cache/uc1/recruit/$CI_PROJECT_NAME/$CI_JOB_ID

push to registry:
  image: docker:git
  stage: release
  extends: .docker_registry
  script:
    - export IMAGE_TAG=$(cat .VERSION)
    - docker pull $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $IMAGE_PATH:v$IMAGE_TAG
    - docker push $IMAGE_PATH:v$IMAGE_TAG
  only:
    - master

git release:
  image: docker.miracum.org/miracum-devops/semantic-release:v17
  stage: release
  script:
    - npx semantic-release
  only:
    - master
