variables:
  CONTAINER_REGISTRY_HOST: ghcr.io
  CONTAINER_PROJECT_PATH: /miracum/recruit/list

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

.registry_login:
  before_script:
    - echo $GHCR_REGISTRY_PASSWORD | docker login -u $GHCR_REGISTRY_USERNAME $CONTAINER_REGISTRY_HOST --password-stdin
  after_script:
    - docker logout $CONTAINER_REGISTRY_HOST

unit:
  stage: test
  image: docker:stable
  extends:
    - .job_defaults
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
  script:
    - docker build --target=test .
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

#e2e:
#  stage: test
#  image:
#    name: docker/compose:1.29.2
#    entrypoint: [""]
#  extends: .job_defaults
#  before_script:
#    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    # removing babel.config.js prevents the error
    # 'Error: Cannot find module '@vue/cli-plugin-babel/preset' from '/e2e' while rsing file: /e2e/tests/e2e/support/index.js'
    # in cypress
#    - rm babel.config.js
#  script:
#    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run loader
#    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run e2e
#  after_script:
#    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml logs
#    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml down -v --remove-orphans

staging:
  stage: deploy
  image:
    name: quay.io/chgl/kube-powertools:latest
    entrypoint: [""]
  script:
    - helm repo add miracum https://harbor.miracum.org/chartrepo/charts
    - helm upgrade --install -n $KUBE_NAMESPACE -f deploy/staging/values.yaml --set list.image.tag=$CI_COMMIT_SHORT_SHA --version ^8.6.2 recruit miracum/recruit
  environment:
    name: staging
    url: https://lists.recruit.miracum.org/
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual

push to miracum registry and sign:
  stage: release
  image: harbor.miracum.org/ci/docker:stable
  # login to GHCR.io to pull the image before re-tagging it to harbor.miracum.org
  before_script:
    - echo $GHCR_REGISTRY_PASSWORD | docker login -u $GHCR_REGISTRY_USERNAME $CONTAINER_REGISTRY_HOST --password-stdin
    - echo $MIRACUM_REGISTRY_PASSWORD | docker login -u $MIRACUM_REGISTRY_USERNAME $MIRACUM_CONTAINER_REGISTRY --password-stdin
    - wget https://github.com/sigstore/cosign/releases/download/v1.0.0/cosign-linux-amd64 -O /usr/local/bin/cosign && chmod +x /usr/local/bin/cosign
  after_script:
    - docker logout $CONTAINER_REGISTRY_HOST
    - docker logout $MIRACUM_CONTAINER_REGISTRY
  script:
    - test -f .NORELEASE && echo ".NORELEASE file detected. Not pushing to avoid creating non-immutable images." && exit 0
    - VERSION=$(cat .VERSION)
    - docker pull $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $MIRACUM_CONTAINER_REGISTRY$CONTAINER_PROJECT_PATH:v$VERSION
    - docker push $MIRACUM_CONTAINER_REGISTRY$CONTAINER_PROJECT_PATH:v$VERSION
    - cosign sign -key $COSIGN_PRIVATE_KEY $MIRACUM_CONTAINER_REGISTRY$CONTAINER_PROJECT_PATH:v$VERSION
    - cosign sign -key $COSIGN_PRIVATE_KEY $CONTAINER_REGISTRY_HOST$CONTAINER_PROJECT_PATH:v$VERSION
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
