image: docker:stable

variables:
  DOCKER_REGISTRY: docker.miracum.org
  IMAGE_PATH: $DOCKER_REGISTRY/uc1-recruit/list

.docker_registry:
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME $DOCKER_REGISTRY --password-stdin
  after_script:
    - docker logout $DOCKER_REGISTRY

stages:
  - lint
  - version
  - build
  - test
  - release
  - deploy

lint dockerfile:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  except:
    - tags

determine next version:
  image: docker.miracum.org/miracum-devops/semantic-release
  stage: version
  script:
    - npx semantic-release --dry-run
    - test -e .VERSION || echo $(git describe --abbrev=0 --tags | tr -d v) > .VERSION
  artifacts:
    paths:
      - .VERSION
    expire_in: 1 hour
  except:
    - tags

build:
  stage: build
  extends: .docker_registry
  script:
    - export VERSION=$(cat .VERSION)
    - docker build -t $IMAGE_PATH:$CI_COMMIT_SHORT_SHA --build-arg VERSION=$VERSION .
    - docker push $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
  except:
    - tags

integration test:
  stage: test
  image:
    name: docker/compose:1.25.0
    entrypoint: ["/bin/sh", "-c"]
  extends: .docker_registry
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - docker-compose -p $CI_PROJECT_NAME-integrationtests -f tests/integration/docker-compose.yml up --abort-on-container-exit
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-integrationtests -f tests/integration/docker-compose.yml down --volumes
  except:
    - tags

push to harbor:
  image: docker:git
  stage: release
  extends: .docker_registry
  script:
    - export IMAGE_TAG=v$(cat .VERSION)
    - docker pull $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $IMAGE_PATH:$IMAGE_TAG
    - docker push $IMAGE_PATH:$IMAGE_TAG
  only:
    - master

git release:
  image: docker.miracum.org/miracum-devops/semantic-release
  stage: release
  script:
    - npx semantic-release
  only:
    - master

staging:
  image:
    name: docker/compose:1.25.0
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  extends: .docker_registry
  script:
    - export IMAGE_TAG=v$(cat .VERSION)
    - docker-compose -p staging-$CI_PROJECT_NAME -f deploy/docker-compose.staging.yml --verbose pull
    - docker-compose -p staging-$CI_PROJECT_NAME -f deploy/docker-compose.staging.yml --verbose up -d
  environment:
    name: staging
    url: https://lists.recruit.miracum.org/
  only:
    - master
  tags:
    - ume
    - uc1
    - recruit
    - staging
