version: "3.7"

services:
  list:
    image: docker.miracum.org/uc1-recruit/list:${IMAGE_TAG}
    restart: always
    environment:
      - FHIR_URL=http://fhir:8080/fhir
    labels:
      - traefik.docker.network=traefik
      - traefik.frontend.rule=Host:lists.recruit.miracum.org
      - traefik.enable=true
      - traefik.port=8080
    networks:
      - traefik
      - recruit-staging

networks:
  recruit-staging:
    external: true
  traefik:
    external: true
