version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.3
    environment:
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"
      validation.requests.enabled: "true"
    ports:
      - "8082:8080"

  loader:
    image: curlimages/curl:7.75.0
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/data:ro
    depends_on:
      - fhir

  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./data/aio-export.json:/tmp/realm.json
    ports:
      - 8083:8080

  fhir-pseudonymizer:
    image: docker.miracum.org/miracum-etl/fhir-pseudonymizer:2.2.3
    environment:
      APIKEY: "fhir-pseudonymizer-api-key"
      JAEGER__ENABLED: "true"
      JAEGER__HOST: "jaeger"
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    ports:
      - 5000:8080
