version: "3.9"

services:
  fhir:
    image: docker.io/hapiproject/hapi:v6.2.2@sha256:9c4e8af94d81ac0049dbb589e4cd855bf78c9c13be6f6844e814c63d63545b44
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
      HAPI_FHIR_ALLOW_MULTIPLE_DELETE: "true"
    ports:
      - 8082:8080

  loader:
    image: curlimages/curl:7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/data:ro
    depends_on:
      - fhir

  jaeger:
    image: jaegertracing/all-in-one:1.41@sha256:a4f4e57343203e58c53874cb0c764b7523b8c3e2a308ebac845ed1b822166351
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 127.0.0.1:16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 4317:4317

  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./data/aio-export.json:/tmp/realm.json
    ports:
      - 8083:8080

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.15.1@sha256:84d60b439bd1535de941a70c578b8e092f2d7091b57b887d55394588c72873de
    environment:
      APIKEY: "fhir-pseudonymizer-api-key"
      TRACING__ENABLED: "true"
      TRACING__JAEGER__AGENTHOST: "jaeger"
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    ports:
      - 5000:8080
