version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v2.4.0
    restart: always
    ports:
      - "${FHIR_PORT:-9090}:8080"
    environment:
      FHIR_VERSION: R4
      SERVER_URL: http://localhost:${FHIR_PORT:-9090}/fhir
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
    depends_on:
      - db

  loader:
    image: byrnedo/alpine-curl:0.1.7
    command: -X POST
             -H "Content-Type:application/json"
             --retry-connrefuse
             --connect-timeout 10
             --max-time 60
             --retry 5
             --retry-delay 10
             --data "@/data/fhir-sample.json"
             http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./data:/data

  db:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
