version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:8.0.2
    ports:
      - "8082:8080"
    environment:
      server.address: "http://localhost:8082/fhir"
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"
      validation.requests.enabled: "true"

  loader:
    image: curlimages/curl:7.70.0
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/sample-data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/sample-data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/sample-data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/sample-data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/sample-data:ro
