version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.3
    ports:
      - "8082:8080"
    environment:
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"
      validation.requests.enabled: "true"

  loader:
    image: curlimages/curl:7.72.0
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/json' --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data '@/data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/data:ro
    depends_on:
      - fhir

  jaeger:
    image: jaegertracing/all-in-one:1.19
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
