version: "3.9"

services:
  fhir:
    image: docker.io/hapiproject/hapi:v6.0.1@sha256:63c98d8be3dadc77b47dca3115490f22bf99512f363f779f7bbcb42f569aeac3
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
      HAPI_FHIR_ALLOW_MULTIPLE_DELETE: "true"
    ports:
      - 8082:8080

  loader:
    image: curlimages/curl:7.84.0@sha256:5a2a25d96aa941ea2fc47acc50122f7c3d007399a075df61a82d6d2c3a567a2b
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/data:ro
    depends_on:
      - fhir

  jaeger:
    image: jaegertracing/all-in-one:1.37@sha256:60ab2e6b0682f79a4e42b2bd2526ac4de80a3a7a1ef136c71dc0cb85e9c50f46
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 127.0.0.1:16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 4317:4317

  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1@sha256:abade9a9cf985b454b30a9119183e62a0018ec546c8fc4fbd8572457afb4a666
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./data/aio-export.json:/tmp/realm.json
    ports:
      - 8083:8080

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.12.0@sha256:2e03bfa1e3cbd2615c3c5b382ee8da1db76c188674108f6a1606482f75051da1
    environment:
      APIKEY: "fhir-pseudonymizer-api-key"
      TRACING__ENABLED: "true"
      TRACING__JAEGER__AGENTHOST: "jaeger"
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    ports:
      - 5000:8080
