version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v7.2.3
    ports:
      - "8082:8080"
    environment:
      server.address: "http://localhost:8082/fhir"
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"

  loader:
    image: curlimages/curl:7.70.0
    command: >
      -X POST
      -H "Content-Type: application/json"
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      --data "@/lists.fhir.sample.json"
      http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./lists.fhir.sample.json:/lists.fhir.sample.json:ro
