version: "3.9"

services:
  fhir:
    image: hapiproject/hapi:v5.4.1
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
    ports:
      - "8082:8080"

  loader:
    image: curlimages/curl:7.77.0
    command: >
      sh -c "curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-1.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-2.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-record-3.json' http://fhir:8080/fhir &&
             curl -X POST -H 'Content-Type:application/fhir+json' --retry-connrefuse --connect-timeout 30 --max-time 60 --retry 5 --retry-delay 15 --data '@/data/sample-lists.json' http://fhir:8080/fhir"
    volumes:
      - ./data:/data:ro
    depends_on:
      - fhir

  jaeger:
    image: jaegertracing/all-in-one:1.24
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./data/aio-export.json:/tmp/realm.json
    ports:
      - 8083:8080

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.7.1
    environment:
      APIKEY: "fhir-pseudonymizer-api-key"
      TRACING__ENABLED: "true"
      TRACING__JAEGER__AGENTHOST: "jaeger"
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    ports:
      - 5000:8080
